spring.application.name=teamvault

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

# Tell Spring Boot that the default active profile is 'dev'.
# This makes it automatically load application-dev.properties locally.
spring.profiles.active=dev
